version: "3.8"

x-common-env: &common-env
  DOMAIN_NAME: ${DOMAIN_NAME}
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USER: ${MYSQL_USER}
  PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
  PHP_MAX_UPLOAD: ${PHP_MAX_UPLOAD}
  PHP_MAX_CHILDREN: ${PHP_MAX_CHILDREN}
  WP_TITLE: ${WP_TITLE}
  WP_ADMIN_USER: ${WP_ADMIN_USER}
  WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
  WP_USER: ${WP_USER}
  WP_USER_EMAIL: ${WP_USER_EMAIL}

x-db-secrets: &db-secrets
  - db_root_password
  - db_password

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:1.0
    container_name: mariadb
    restart: always
    env_file: ./.env
    environment:
      <<: *common-env
    secrets: *db-secrets
    networks: [inception]
    volumes:
      - type: bind
        source: /home/${LOGIN}/data/mariadb
        target: /var/lib/mysql

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:1.0
    container_name: wordpress
    restart: always
    env_file: ./.env
    environment:
      <<: *common-env
    secrets: *db-secrets
    depends_on: [mariadb]
    networks: [inception]
    volumes:
      - type: bind
        source: /home/${LOGIN}/data/wordpress
        target: /var/www/html

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:1.0
    container_name: nginx
    restart: always
    env_file: ./.env
    environment:
      <<: *common-env
    depends_on: [wordpress]
    networks: [inception]
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: /home/${LOGIN}/data/wordpress
        target: /var/www/html
        read_only: true

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt